handle scrape errors

diff --git a/wd b/wd
--- a/wd
+++ b/wd
@@ -1,4 +1,5 @@
-#!/usr/bin/env bash
+#!/opt/local/bin/bash
+
 set -euo pipefail
 IFS=$'\n\t'
 shopt -s nullglob nocaseglob
@@ -84,8 +85,8 @@ fi
 
 # do the download
 if [[ $DOWNLOAD == 0 ]]; then
-  wget --no-check-certificate --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 "https://cdn.star.nesdis.noaa.gov/GOES17/ABI/SECTOR/np/GEOCOLOR/latest.jpg" -O "$SCRIPT_DIR/assets/GOES17_north_pacific.jpg" &
-  wget --no-check-certificate --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 "https://images.wsdot.wa.gov/nc/002vc06430.jpg" -O "$SCRIPT_DIR/assets/wsdot_stevens_pass.jpg" &
+  wget --no-check-certificate --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=60 -4 "https://cdn.star.nesdis.noaa.gov/GOES18/ABI/SECTOR/np/GEOCOLOR/latest.jpg" -O "$SCRIPT_DIR/assets/GOES18_north_pacific.jpg" &
+  wget --no-check-certificate --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 "https://images.wsdot.wa.gov/nc/002vc06430.jpg" -O "$SCRIPT_DIR/assets/wsdot_stevens_pass.jpg" 
   wget --no-check-certificate --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 "https://images.wsdot.wa.gov/nw/002vc04558.jpg" -O "$SCRIPT_DIR/assets/wsdot_us2_skykomish.jpg" &
   wget --no-check-certificate --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 "https://images.wsdot.wa.gov/nc/002vc06458.jpg" -O "$SCRIPT_DIR/assets/wsdot_e_stevens_summit.jpg" &
   wget --no-check-certificate --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 "https://images.wsdot.wa.gov/nc/002vc06300.jpg" -O "$SCRIPT_DIR/assets/wsdot_big_windy.jpg" &
@@ -97,6 +98,9 @@ if [[ $DOWNLOAD == 0 ]]; then
   wget --no-check-certificate --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 "https://live8p.brownrice.com/cam-images/stevenspassjupiter.jpg" -O "$SCRIPT_DIR/assets/stevenspassjupiter.jpg" &
 fi
 
+# wait for downloads to complete, useful for debugging
+# wait
+
 # setup python venv and run shot scraper
 if [[ $SCRAPE == 0 ]]; then
   if ! [[ -d "${SCRIPT_DIR}/.venv_scrape" ]]; then
@@ -106,12 +110,34 @@ if [[ $SCRAPE == 0 ]]; then
     pip install --upgrade pip
     pip install shot-scraper
   else
+    echo "scraping sites..."
+    # need to add error handling for shot-scraper so that if it fails to grab image a transparent png is used
     source "${SCRIPT_DIR}/.venv_scrape/bin/activate"
-    shot-scraper 'https://forecast.weather.gov/MapClick.php?lat=47.7456&lon=-121.0892&unit=0&lg=english&FcstType=graphical' -o "${SCRIPTPATH}/assets/weather_gov_hourly_forecast.png" --selector 'body > table:nth-child(6)'
-    shot-scraper 'https://forecast.weather.gov/MapClick.php?lat=47.7456&lon=-121.0892' -o "${SCRIPTPATH}/assets/weather_gov_extended_forecast.png" --selector '#seven-day-forecast'
-    shot-scraper 'https://nwac.us/data-portal/graph/21/' -o "${SCRIPTPATH}/assets/nwac_stevens_observations.png" --selector '#post-146 > div' --wait 5000
-    shot-scraper 'https://nwac.us/avalanche-forecast/#/stevens-pass' -o "${SCRIPTPATH}/assets/nwac_stevens_avalanche_forcast.png" --selector '#nac-forecast-container > div > div.nac-card.nac-content-panel.nac-content-panel-tab > div > div.pswipe-gallery > div > div.nac-danger.nac-mb-4' --wait 1000
-    shot-scraper 'https://nwac.us' -o "${SCRIPTPATH}/assets/nwac_avalanche_forcast.png" --selector '#danger-map-widget' --wait 1000
+    echo "scraping weather_gov_hourly_forecast.png"
+    if ! shot-scraper 'https://forecast.weather.gov/MapClick.php?lat=47.7456&lon=-121.0892&unit=0&lg=english&FcstType=graphical' -o "${SCRIPTPATH}/assets/weather_gov_hourly_forecast.png" --selector 'body > table:nth-child(6)';then
+      echo "weather_gov_hourly_forecast.png failed"
+      convert -size 1x1 xc:none "${SCRIPTPATH}/assets/weather_gov_hourly_forecast.png"
+    fi
+    echo "scraping weather_gov_extended_forecast.png"
+    if ! shot-scraper 'https://forecast.weather.gov/MapClick.php?lat=47.7456&lon=-121.0892' -o "${SCRIPTPATH}/assets/weather_gov_extended_forecast.png" --selector '#seven-day-forecast';then
+      echo "weather_gov_extended_forecast.png failed"
+      convert -size 1x1 xc:none "${SCRIPTPATH}/assets/weather_gov_extended_forecast.png"
+    fi
+    echo "scraping nwac"
+    if ! shot-scraper 'https://nwac.us/data-portal/graph/21/' -o "${SCRIPTPATH}/assets/nwac_stevens_observations.png" --selector '#post-146 > div' --wait 5000;then
+      echo "nwac_stevens_observations.png failed"
+      convert -size 1x1 xc:none "${SCRIPTPATH}/assets/nwac_stevens_observations.png"
+    fi
+    echo "scraping nwac avalanche forcast"
+    if ! shot-scraper 'https://nwac.us/avalanche-forecast/#/stevens-pass' -o "${SCRIPTPATH}/assets/nwac_stevens_avalanche_forcast.png" --selector '#nac-forecast-container > div > div.nac-card.nac-content-panel.nac-content-panel-tab > div > div.pswipe-gallery > div > div.nac-danger.nac-mb-4' --wait 1000;then
+      echo "nwac_stevens_avalanche_forcast.png failed"
+      convert -size 1x1 xc:none "${SCRIPTPATH}/assets/nwac_stevens_avalanche_forcast.png"
+    fi
+    echo "scraping nwac avalanche forcast map"
+    if ! shot-scraper 'https://nwac.us' -o "${SCRIPTPATH}/assets/nwac_avalanche_forcast.png" --selector '#danger-map-widget' --wait 1000;then
+      echo "nwac_avalanche_forcast.png failed"
+      convert -size 1x1 xc:none "${SCRIPTPATH}/assets/nwac_avalanche_forcast.png"
+    fi
   fi
 fi
 
@@ -123,9 +149,10 @@ fi
 
 # crop and resize
 if [[ $CROP == 0 ]]; then
-  convert "$SCRIPT_DIR/assets/GOES17_north_pacific.jpg" -crop 7200x4050+0+0 -resize "3840>" "$SCRIPT_DIR/assets/background_s.jpg" &
+  echo "croping images..."
+  convert "$SCRIPT_DIR/assets/GOES18_north_pacific.jpg" -crop 7200x4050+0+0 -resize "3840>" "$SCRIPT_DIR/assets/background_s.jpg" &
   convert "$SCRIPT_DIR/assets/nwac_avalanche_forcast.png" -crop 400x520+65+110 -resize "100%" "$SCRIPT_DIR/assets/nwac_avalanche_forcast_s.jpg" &
-  convert "$SCRIPT_DIR/assets/nwac_stevens_avalanche_forcast.png" -crop 1086x380+0+25 -resize "100%" "$SCRIPT_DIR/assets/nwac_stevens_avalanche_forcast_s.jpg" &
+#  convert "$SCRIPT_DIR/assets/nwac_stevens_avalanche_forcast.png" -crop 1086x380+0+25 -resize "100%" "$SCRIPT_DIR/assets/nwac_stevens_avalanche_forcast_s.jpg" &
   convert "$SCRIPT_DIR/assets/nwac_stevens_observations.png" -crop 1140x1439+0+0 -resize "75%" "$SCRIPT_DIR/assets/nwac_stevens_observations_s.jpg" &
   convert "$SCRIPT_DIR/assets/weather_gov_hourly_forecast.png" -crop 806x930+0+200 -resize "106%" "$SCRIPT_DIR/assets/weather_gov_hourly_forecast_s.jpg" &
   convert "$SCRIPT_DIR/assets/stevenspasscourtyard.jpg" -crop 1920x1080+0+0 -resize "50%" "$SCRIPT_DIR/assets/stevenspasscourtyard_s.jpg" &
@@ -140,12 +167,14 @@ if [[ $CROP == 0 ]]; then
 fi
 
 # composit the image
+#    "$SCRIPT_DIR/assets/nwac_stevens_avalanche_forcast_s.jpg" -geometry +2730+20 -composite \
+
 if [[ $RENDER == 0 ]]; then
+  echo "Rendering..."
   convert -size 3840x2160 xc:skyblue \
     "$SCRIPT_DIR/assets/background_s.jpg" -geometry +0+0 -composite \
     "$SCRIPT_DIR/assets/weather_gov_hourly_forecast_s.jpg" -geometry +20+1130 -composite \
     "$SCRIPT_DIR/assets/weather_gov_extended_forecast_s.jpg" -geometry +2680+1860 -composite \
-    "$SCRIPT_DIR/assets/nwac_stevens_avalanche_forcast_s.jpg" -geometry +2730+20 -composite \
     "$SCRIPT_DIR/assets/nwac_avalanche_forcast_s.jpg" -geometry +3420+420 -composite \
     "$SCRIPT_DIR/assets/nwac_stevens_observations_s.jpg" -geometry +20+20 -composite \
     "$SCRIPT_DIR/assets/wsdot_us2_skykomish.jpg" -geometry +900+20 -composite \
